<a href="https://colab.research.google.com/github/SandipanMukhopadhyay/Credit_Card_Fraud/blob/main/Credit_card_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the Dependencies

In [31]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [32]:
#loadng the dataset into pandas dataframe
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [33]:
#first five rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [34]:
#last five rows of the dataset
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [35]:
# dataset information
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [36]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [38]:
# checking the distribution of legit transaction and fradulent transaction
credit_card_data['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

This dataset is highly unbalanced

0 --> Normal Transaction
1 --> Fradulent Transaction

In [39]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [40]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [41]:
# statistical measures of the data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [42]:
# statistical measures of the data
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [43]:
# Compare the values for both transaction
credit_card_data.groupby('Class').mean

Under-sampling

Build a sample dataset containing similar distribution of normal transactions and Fradulent Transactions

Number of fradulent transaction -->492

In [44]:
legit_sample = legit.sample(n=492)

Concatinating Two DataFrames

In [45]:
new_dataset = pd.concat([legit_sample,fraud],axis=0)

In [46]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
182723,125522.0,-2.993007,2.232973,0.876023,0.460081,0.224338,0.224558,1.386027,-1.523587,3.343156,...,-0.631935,-0.973712,0.131723,-0.211718,-0.841465,-1.318970,-2.203626,-0.277409,14.99,0
224849,143992.0,-1.287375,2.451242,-2.445448,0.391525,0.936526,-0.142964,0.351907,1.154414,-1.278866,...,0.320278,0.850983,-0.173360,-0.337012,-0.025536,-0.355725,0.305025,0.210887,2.00,0
122491,76581.0,1.099678,-1.192628,0.913261,-0.518376,-1.590131,0.075743,-1.070158,0.153706,-0.364156,...,-0.195273,-0.231964,-0.094724,0.052049,0.068309,1.102154,-0.036061,0.025428,119.00,0
191517,129291.0,-2.244938,0.142779,-1.653244,-0.545750,1.397824,-1.075334,2.259868,-0.266979,-0.733910,...,-0.154641,-0.642317,-0.438936,-1.215607,1.147298,0.757576,-0.383450,-0.283150,310.00,0
255244,157132.0,1.962739,-0.877144,-0.606290,-0.246707,-0.966073,-0.631265,-0.536002,-0.068901,-0.240660,...,-0.743389,-1.704336,0.516012,-0.047368,-0.638969,-0.871124,0.023880,-0.031742,60.89,0

In [47]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [48]:
new_dataset['Class'].value_counts()

0    492
1    492
Name: Class, dtype: int64

In [49]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,95198.815041,0.062458,-0.019873,0.028981,-0.042714,-0.037664,0.008533,-0.032994,0.086729,-0.010503,...,0.001099,-0.039748,-0.063903,0.051701,0.009733,0.008849,-0.035413,-0.005336,-0.001659,84.882337
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

Splitting the data into Features and Target

In [50]:
X = new_dataset.drop(columns='Class',axis=1)
Y = new_dataset['Class']

In [51]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
182723  125522.0 -2.993007  2.232973  0.876023  0.460081  0.224338  0.224558
224849  143992.0 -1.287375  2.451242 -2.445448  0.391525  0.936526 -0.142964
122491   76581.0  1.099678 -1.192628  0.913261 -0.518376 -1.590131  0.075743
191517  129291.0 -2.244938  0.142779 -1.653244 -0.545750  1.397824 -1.075334
255244  157132.0  1.962739 -0.877144 -0.606290 -0.246707 -0.966073 -0.631265
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
182723  1.386027 -1.523587  3.343156  ...  0.595980 -0.631935 -0.973712
224849  0.351907  1.154414 -1.278866  ...  0.033842  0.320278  0.850983
122491 -1.070158  0.153706 -0.364156  ... -0.231245 -0.195273 -0.231964
191517  2.259868 -0.266979 -0.733910  ...  0.195926 -0.154641 -0.642317
255244 -0.536002 -0.068901 -0.240660  ... -0.549787 -0.743389 -1.704336
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
182723  0.131723 -0.211718 -0.841465 -1.318970 -2.203626 -0.277409   14.99
224849 -0.173360 -0.337012 -0.025536 -0.355725  0.305025  0.210887    2.00
122491 -0.094724  0.052049  0.068309  1.102154 -0.036061  0.025428  119.00
191517 -0.438936 -1.215607  1.147298  0.757576 -0.383450 -0.283150  310.00
255244  0.516012 -0.047368 -0.638969 -0.871124  0.023880 -0.031742   60.89
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [52]:
print(Y)

182723    0
224849    0
122491    0
191517    0
255244    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

Splitting the data into Training data and Testing data

In [53]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.2, stratify=Y, random_state=2)

In [54]:
print(X.shape,X_train.shape,X_test.shape)

(984, 30) (787, 30) (197, 30)

Model Training

In [55]:
model = LogisticRegression()

In [56]:
# training the Logistic Regression Model with training data
model.fit(X_train,Y_train)

LogisticRegression()

Model Evaluation

Accuracy Score

In [58]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

In [59]:
print('Accuracy score on training data: ',training_data_accuracy)

Accuracy score on training data:  0.9263024142312579

In [61]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,Y_test)

In [62]:
print('Accuracy score on test data: ',test_data_accuracy)

Accuracy score on test data:  0.9086294416243654